# Generated by Django 5.1.1 on 2024-10-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veg_name', models.CharField(max_length=200)),
                ('veg_price', models.IntegerField()),
                ('veg_image', models.ImageField(default='default_image.jpg', upload_to='vegetables')),
            ],
        ),
    ]
