# Generated by Django 5.1.1 on 2024-10-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_contname_contact_contactname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contnumb',
            new_name='contnumber',
        ),
        migrations.AlterField(
            model_name='contact',
            name='contactname',
            field=models.CharField(max_length=50, unique=True, verbose_name='ContactName'),
        ),
    ]
