# Generated by Django 5.1.1 on 2024-10-17 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_contnumb_contact_contnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contnumber',
            new_name='contnumb',
        ),
    ]
