# Generated by Django 5.1.1 on 2024-10-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_contnumber_contact_contnumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contactname',
        ),
        migrations.AddField(
            model_name='contact',
            name='contname',
            field=models.CharField(default=1, max_length=50, unique=True),
        ),
    ]
